--------------------------------------------------------
--  File created - Thursday-January-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type LOGMNR$COL_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$COL_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
MD_COL_NAME VARCHAR2(384),
MD_COL_NUM NUMBER,                 /* col# */
MD_COL_SEGCOL NUMBER,              /* segcol# */
MD_COL_TYPE NUMBER,                /* type# */
MD_COL_LEN NUMBER,
MD_COL_PREC NUMBER,                /* precision */
MD_COL_SCALE NUMBER,
MD_COL_CHARSETID NUMBER,           /* character set id */
MD_COL_CHARSETFORM NUMBER,         /* character set form */
MD_COL_ALT_TYPE VARCHAR2(4000),    /* adt type if any */
MD_COL_ALT_PREC NUMBER,            /* precision of the adt attribute */
MD_COL_ALT_CHAR_USED VARCHAR2(2),  /* charset used by the adt attribute */
MD_COL_ALT_LENGTH NUMBER,          /* length of the adt attribute */
MD_COL_ALT_XML_TYPE NUMBER,        /* 0/1. is xml_type column */
MD_COL_ALT_BINARYXML_TYPE NUMBER,  /* 0/1. is xml_type stored as binary */
MD_COL_ENC_ISENC VARCHAR2(3) ,     /* 'YES'/'NO' */
MD_COL_ENC_NOSALT VARCHAR2(3) ,    /* 'YES'/'NO' */
MD_COL_ENC_ISLOB VARCHAR2(3) ,     /* 'YES'/'NO' */
MD_COL_ALT_OBJECTXML_TYPE NUMBER,  /* 0/1 xml_type stored as object */
MD_COL_HASNOTNULLDEFAULT VARCHAR2(3) ,   /* 'YES'/'NO' */
MD_COL_ALT_TYPE_OWNER VARCHAR2(384),  /* owner of the adt type if any */
PROPERTY NUMBER,
XCOLTYPEFLAGS NUMBER,
XOPQTYPEFLAGS NUMBER,
EAFLAGS NUMBER,
XFQCOLNAME VARCHAR2(4000),
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000),
/* Following fields added in 12.1.0.2 */
OBJV# NUMBER,
INTCOL# NUMBER,
INTERVAL_LEADING_PRECISION NUMBER,
INTERVAL_TRAILING_PRECISION NUMBER,
TOID RAW(16),
TYPENAME VARCHAR2(384),
NUMINTCOLS NUMBER,
NUMATTRS NUMBER,
ADTORDER NUMBER,
LOGMNR_SPARE1 NUMBER,
LOGMNR_SPARE2 NUMBER,
LOGMNR_SPARE3 VARCHAR2(1000),
LOGMNR_SPARE4 DATE,
LOGMNR_SPARE5 NUMBER,
LOGMNR_SPARE6 NUMBER,
LOGMNR_SPARE7 NUMBER,
LOGMNR_SPARE8 NUMBER,
LOGMNR_SPARE9 NUMBER,
XTYPENAME VARCHAR2(4000),
XTOPINTCOL NUMBER,
XREFFEDTABLEOBJN NUMBER,
XREFFEDTABLEOBJV NUMBER,
XOPQTYPETYPE NUMBER,
XOPQLOBINTCOL NUMBER,
XOPQOBJINTCOL NUMBER,
XXMLINTCOL    NUMBER,
LOGMNRDERIVEDFLAGS NUMBER,
/* Following fields added in 12.2 */
COLLID      NUMBER,
COLLINTCOL#  NUMBER,
ACDRRESCOL# NUMBER
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$COL_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$COL_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$COL_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$GSBA_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$GSBA_GG_REC" AS OBJECT
(
LOGMNR_UID NUMBER,
NAME           VARCHAR2(384),
VALUE          VARCHAR2(4000),
LOGMNR_SPARE1  NUMBER,
LOGMNR_SPARE2  NUMBER,
LOGMNR_SPARE3  VARCHAR2(4000),
LOGMNR_SPARE4  DATE
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$GSBA_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$GSBA_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$GSBA_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$KEY_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$KEY_GG_REC" as object
(
LOGMNR_UID NUMBER,
KEY# NUMBER,                   /* index obj# or con# */
KEY_FLAGS NUMBER,              /* index or constraint */
KEY_NAME VARCHAR2(384),        /* index name or constraint name */
INDEX_OWNER# NUMBER,
INDEX_OWNERNAME VARCHAR2(384),
COLNAME VARCHAR2(384),
INTCOL# NUMBER,
which number,
KEY_ORDER VARCHAR2(10),              /* asc or desc */
KEYCOL_FLAGS NUMBER,           /* Column properties such as is_null */
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000)
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$KEY_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$KEY_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$KEY_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$SEQ_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$SEQ_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
NAME VARCHAR2(384),
OWNER# NUMBER,
OWNERNAME VARCHAR2(384),
FLAGS NUMBER,
MD_TAB_SEQCACHE NUMBER,
MD_TAB_SEQINCREMENTBY NUMBER,
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000)
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$SEQ_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$SEQ_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$SEQ_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$TAB_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$TAB_GG_REC" as object
(
LOGMNR_UID NUMBER,
OBJ# NUMBER,
BASEOBJV# NUMBER,
MD_TAB_USERID NUMBER,                /* owner# */
MD_TAB_COLCOUNT NUMBER,              /* user column count */
MD_TAB_TOTAL_COL_NUM NUMBER,         /* kernal column count */
MD_TAB_LOG_GROUP_EXISTS NUMBER,      /* Any log group exists for this table */
MD_TAB_IOT VARCHAR2(3) ,             /* 'YES'/'NO' IS IOT? */
MD_TAB_IOT_OVERFLOW VARCHAR2(3) ,    /* 'YES'/'NO' IOT with overflow ? */
MD_TAB_PARTITION  VARCHAR2(3) ,      /* 'YES'/'NO' is partitioned ? */
MD_TAB_SUBPARTITION VARCHAR2(3) ,    /* 'YES'/'NO' is sub partitioned? */
MD_TAB_XMLTYPETABLE VARCHAR2(3) ,    /* 'YES'/'NO' is xmltype table? */
MD_TAB_OBJECTID NUMBER,              /* object id if table object */
MD_TAB_OWNER VARCHAR2(384),     /* owner name */
MD_TAB_NAME VARCHAR2(384),      /* table name */
MD_TAB_OBJTYPE VARCHAR2(384),   /* Object type name */
MD_TAB_SCN NUMBER,                   /* COMMIT_SCN of this table version */
TAB_FLAGS NUMBER,
TRIGFLAG NUMBER,
OBJ_FLAGS NUMBER,
PROPERTY NUMBER,
PARTTYPE NUMBER,
SUBPARTTYPE NUMBER,
SPARE1  NUMBER,
SPARE2  NUMBER,
SPARE3  NUMBER,
SPARE4  VARCHAR2(4000),
SPARE5  VARCHAR2(4000),
SPARE6  VARCHAR2(4000),
/* Following fields added in 12.1.0.2 */
LVLCNT NUMBER,
LVL1OBJ# NUMBER,
LVL2OBJ# NUMBER,
LVL1TYPE# NUMBER,
LVL2TYPE# NUMBER,
LVL1NAME  VARCHAR2(384),
LVL2NAME  VARCHAR2(384),
INTCOLS   NUMBER,
ASSOC#    NUMBER,
XIDUSN    NUMBER,
XIDSLT    NUMBER,
XIDSQN    NUMBER,
DROP_SCN  NUMBER,
FLAGS     NUMBER,
LOGMNR_SPARE1   NUMBER,
LOGMNR_SPARE2   NUMBER,
LOGMNR_SPARE3   VARCHAR2(1000),
LOGMNR_SPARE4   DATE,
LOGMNR_SPARE5   NUMBER,
LOGMNR_SPARE6   NUMBER,
LOGMNR_SPARE7   NUMBER,
LOGMNR_SPARE8   NUMBER,
LOGMNR_SPARE9   NUMBER,
UNSUPPORTEDCOLS  NUMBER,
COMPLEXTYPECOLS  NUMBER,
NTPARENTOBJNUM   NUMBER,
NTPARENTOBJVERSION NUMBER,
NTPARENTINTCOLNUM  NUMBER,
LOGMNRTLOFLAGS    NUMBER,
LOGMNRMCV VARCHAR2(30),
/* Following fields added in 12.2 */
ACDRFLAGS        NUMBER,                                    /* automatic CDR */
ACDRTSOBJ#       NUMBER,                                    /* automatic CDR */
ACDRROWTSINTCOL# NUMBER                                     /* automatic CDR */
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$TAB_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$TAB_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$TAB_GG_REC;

/
--------------------------------------------------------
--  DDL for Type LOGMNR$USER_GG_REC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$USER_GG_REC" AS OBJECT
(
LOGMNR_UID     NUMBER,
USERNAME       VARCHAR2(384),
USERID         NUMBER,
LOGMNR_SPARE1  NUMBER,
LOGMNR_SPARE2  NUMBER,
LOGMNR_SPARE3  VARCHAR2(4000),
LOGMNR_SPARE4  DATE
);

/
--------------------------------------------------------
--  DDL for Type LOGMNR$USER_GG_RECS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "SYSTEM"."LOGMNR$USER_GG_RECS" AS TABLE OF  SYSTEM.LOGMNR$USER_GG_REC;

/
--------------------------------------------------------
--  DDL for Sequence CATALOG_UNIVERSITATE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."CATALOG_UNIVERSITATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DISCIPLINE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."DISCIPLINE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGMNR_DIDS$
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."LOGMNR_DIDS$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGMNR_EVOLVE_SEQ$
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."LOGMNR_EVOLVE_SEQ$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGMNR_SEQ$
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."LOGMNR_SEQ$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGMNR_UIDS$
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."LOGMNR_UIDS$"  MINVALUE 100 MAXVALUE 99999 INCREMENT BY 1 START WITH 100 NOCACHE  ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MVIEW$_ADVSEQ_GENERIC
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."MVIEW$_ADVSEQ_GENERIC"  MINVALUE 1 MAXVALUE 4294967295 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MVIEW$_ADVSEQ_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."MVIEW$_ADVSEQ_ID"  MINVALUE 1 MAXVALUE 4294967295 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PREZENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."PREZENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROLLING_EVENT_SEQ$
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."ROLLING_EVENT_SEQ$"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STUDENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."STUDENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATALOG_UNIVERSITATE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CATALOG_UNIVERSITATE" 
   (	"ID_NOTA" NUMBER, 
	"DATA" DATE, 
	"NR_MATRICOL" NUMBER, 
	"ID_D" NUMBER, 
	"PUNCTAJ" NUMBER(4,2), 
	"TIP" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISCIPLINE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DISCIPLINE" 
   (	"ID" NUMBER, 
	"NUME_DISCIPLINA" VARCHAR2(20 BYTE), 
	"PREZENTE_MINIME_NANG" NUMBER DEFAULT 10, 
	"PREZENTE_MINIME_ANG" NUMBER DEFAULT 7, 
	"NR_TESTE" NUMBER DEFAULT 0, 
	"PROCENT_TESTE" NUMBER, 
	"PROCENT_EXAMEN" NUMBER, 
	"BONUS" NUMBER(1,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISCIPLINE_STUDENTI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DISCIPLINE_STUDENTI" 
   (	"NR_MATRICOL" NUMBER, 
	"ID_D" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREZENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PREZENTE" 
   (	"ID_PREZ" NUMBER, 
	"DATA" DATE, 
	"NR_MATRICOL" NUMBER, 
	"ID_D" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENTI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENTI" 
   (	"NR_MATRICOL" NUMBER, 
	"CNP" CHAR(13 BYTE), 
	"NUME" VARCHAR2(20 BYTE), 
	"PRENUME" VARCHAR2(20 BYTE), 
	"NRTEL" CHAR(10 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"ADRESA" VARCHAR2(100 BYTE), 
	"SOLD" NUMBER(10,3) DEFAULT 0, 
	"ANGAJAT" NUMBER(1,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View DISCIPLINE_STUDENTI_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."DISCIPLINE_STUDENTI_VIEW" ("NR_MATRICOL", "CNP", "NUME", "PRENUME", "ID_D", "NUME_DISCIPLINA", "PREZENTE_MINIME", "PREZENTE_STUDENT", "MEDIA") AS 
  (
SELECT S.NR_MATRICOL, S.CNP, S.NUME, S.PRENUME, D.ID ID_D, D.NUME_DISCIPLINA,
CASE WHEN S.ANGAJAT = 1 THEN D.PREZENTE_MINIME_ANG
ELSE D.PREZENTE_MINIME_NANG
END AS PREZENTE_MINIME, NVL(NPV.PREZENTE_STUDENT,0), MSV.MEDIA
FROM DISCIPLINE_STUDENTI DS
    LEFT JOIN STUDENTI S
            ON S.NR_MATRICOL = DS.NR_MATRICOL
    LEFT JOIN DISCIPLINE D
            ON D.ID = DS.ID_D
    LEFT JOIN NUMAR_PREZENTE_VIEW NPV
            ON NPV.NR_MATRICOL = DS.NR_MATRICOL AND NPV.ID_D = DS.ID_D
    LEFT JOIN MEDII_STUDENT_VIEW MSV
            ON MSV.NR_MATRICOL = DS.NR_MATRICOL AND MSV.ID_D = DS.ID_D
    )
;
--------------------------------------------------------
--  DDL for View MEDII_STUDENT_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MEDII_STUDENT_VIEW" ("NR_MATRICOL", "ID_D", "MEDIA") AS 
  (
SELECT NCV.NR_MATRICOL, NCV.ID_D, 
CASE 
WHEN ROUND(NCV.MEDIE_TESTE*(D.PROCENT_TESTE/100)+NCV.NOTA_EXAMEN*(D.PROCENT_EXAMEN/100)+NCV.PUNCTE_BONUS) < 10
    THEN ROUND(NCV.MEDIE_TESTE*(D.PROCENT_TESTE/100)+NCV.NOTA_EXAMEN*(D.PROCENT_EXAMEN/100)+NCV.PUNCTE_BONUS)
ELSE 10
END AS MEDIE_DISCIPLINA
FROM NOTE_CENTRALIZATE_VIEW NCV
JOIN DISCIPLINE D
ON D.ID = NCV.ID_D
)
;
--------------------------------------------------------
--  DDL for View NOTE_CENTRALIZATE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."NOTE_CENTRALIZATE_VIEW" ("NR_MATRICOL", "ID_D", "MEDIE_TESTE", "NOTA_EXAMEN", "PUNCTE_BONUS") AS 
  (
    SELECT DS.NR_MATRICOL, DS.ID_D, ROUND(NVL(TESTE.MEDIE_TESTE,0)) , ROUND(NVL(EXAMEN.NOTA_EXAMEN,0)), NVL(BONUS.PUNCTE_BONUS,0)
    FROM DISCIPLINE_STUDENTI DS
    LEFT JOIN
    (
        SELECT ST.NR_MATRICOL,ST.ID_D, ST.SUMA_TESTE/D.NR_TESTE MEDIE_TESTE
        FROM
        (
            SELECT CU.NR_MATRICOL, CU.ID_D , SUM(ROUND(CU.PUNCTAJ)) SUMA_TESTE
            FROM CATALOG_UNIVERSITATE CU
            WHERE CU.TIP = 'T'
            GROUP BY CU.NR_MATRICOL,CU.ID_D
        ) ST
        ,DISCIPLINE D
        WHERE D.ID = ST.ID_D
    ) TESTE
    ON DS.NR_MATRICOL = TESTE.NR_MATRICOL AND DS.ID_D = TESTE.ID_D
    LEFT JOIN
    (
        SELECT NR_MATRICOL, ID_D, PUNCTAJ NOTA_EXAMEN
        FROM CATALOG_UNIVERSITATE
        WHERE TIP = 'E'
    ) EXAMEN
    ON DS.NR_MATRICOL = EXAMEN.NR_MATRICOL AND DS.ID_D = EXAMEN.ID_D
    LEFT JOIN
    (
        SELECT NR_MATRICOL,ID_D,SUM(PUNCTAJ) PUNCTE_BONUS
        FROM CATALOG_UNIVERSITATE
        WHERE TIP = 'B'
        GROUP BY NR_MATRICOL,ID_D
    ) BONUS
    ON DS.NR_MATRICOL = BONUS.NR_MATRICOL AND DS.ID_D = BONUS.ID_D
    )
;
--------------------------------------------------------
--  DDL for View NOTE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."NOTE_VIEW" ("ID_NOTA", "NR_MATRICOL", "CNP", "DATA", "NUME_DISCIPLINA", "PUNCTAJ", "TIP") AS 
  SELECT CU.ID_NOTA,CU.NR_MATRICOL,S.CNP,CU.DATA, D.NUME_DISCIPLINA, CU.PUNCTAJ,CU.TIP
FROM CATALOG_UNIVERSITATE CU, DISCIPLINE D, STUDENTI S
WHERE CU.ID_D = D.ID AND CU.NR_MATRICOL = S.NR_MATRICOL
ORDER BY CU.DATA DESC
;
--------------------------------------------------------
--  DDL for View NUMAR_PREZENTE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."NUMAR_PREZENTE_VIEW" ("NR_MATRICOL", "ID_D", "PREZENTE_STUDENT") AS 
  SELECT NR_MATRICOL, ID_D, COUNT(*) PREZENTE_STUDENT
FROM PREZENTE
GROUP BY NR_MATRICOL, ID_D
;
--------------------------------------------------------
--  DDL for View NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW" ("NR_MATRICOL", "ID_D", "NR_TESTE") AS 
  (
SELECT DS.NR_MATRICOL, DS.ID_D, NVL(NTSMV.NUMAR_TESTE_DISCIPLINA,0)
FROM DISCIPLINE_STUDENTI DS 
LEFT JOIN NUMAR_TESTE_STUDENT_MVIEW NTSMV
ON DS.NR_MATRICOL = NTSMV.NR_MATRICOL AND DS.ID_D = NTSMV.ID_D
)
;
--------------------------------------------------------
--  DDL for View PREZENTE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."PREZENTE_VIEW" ("ID_PREZ", "DATA", "NR_MATRICOL", "CNP", "ID_D", "NUME_DISCIPLINA") AS 
  SELECT P.ID_PREZ, P.DATA, P.NR_MATRICOL, S.CNP, P.ID_D, D.NUME_DISCIPLINA
FROM PREZENTE P, STUDENTI S, DISCIPLINE D
WHERE S.NR_MATRICOL = P.NR_MATRICOL AND P.ID_D = D.ID
ORDER BY P.DATA DESC
;
--------------------------------------------------------
--  DDL for Materialized View NUMAR_TESTE_STUDENT_MVIEW
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "SYSTEM"."NUMAR_TESTE_STUDENT_MVIEW" ("NR_MATRICOL", "ID_D", "NUMAR_TESTE_DISCIPLINA")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  REFRESH FORCE ON COMMIT
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT NR_MATRICOL, ID_D, COUNT(*) NUMAR_TESTE_DISCIPLINA
FROM CATALOG_UNIVERSITATE
WHERE TIP = 'T'
GROUP BY NR_MATRICOL, ID_D;

  CREATE UNIQUE INDEX "SYSTEM"."I_SNAP$_NUMAR_TESTE_STUDENT_MVIEW" ON "SYSTEM"."NUMAR_TESTE_STUDENT_MVIEW" (SYS_OP_MAP_NONNULL("NR_MATRICOL"), SYS_OP_MAP_NONNULL("ID_D")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON MATERIALIZED VIEW "SYSTEM"."NUMAR_TESTE_STUDENT_MVIEW"  IS 'snapshot table for snapshot SYSTEM.NUMAR_TESTE_STUDENT_MVIEW';
--------------------------------------------------------
--  DDL for Index CATALOG_UNIVERSITATE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CATALOG_UNIVERSITATE_PK1" ON "SYSTEM"."CATALOG_UNIVERSITATE" ("ID_NOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATALOG_UNIVERSITATE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CATALOG_UNIVERSITATE_UK" ON "SYSTEM"."CATALOG_UNIVERSITATE" ("NR_MATRICOL", "ID_D", "DATA", "TIP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CNP_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CNP_UK" ON "SYSTEM"."STUDENTI" ("CNP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISCIPLINE_NUME_DISCIPLINA_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DISCIPLINE_NUME_DISCIPLINA_UK" ON "SYSTEM"."DISCIPLINE" ("NUME_DISCIPLINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISCIPLINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DISCIPLINE_PK" ON "SYSTEM"."DISCIPLINE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INREGISTRARI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INREGISTRARI_PK" ON "SYSTEM"."DISCIPLINE_STUDENTI" ("NR_MATRICOL", "ID_D") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSOANE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERSOANE_PK" ON "SYSTEM"."STUDENTI" ("NR_MATRICOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREZENTE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREZENTE_PK1" ON "SYSTEM"."PREZENTE" ("ID_PREZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREZENTE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREZENTE_UK" ON "SYSTEM"."PREZENTE" ("DATA", "NR_MATRICOL", "ID_D") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATALOG_UNIVERSITATE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CATALOG_UNIVERSITATE_PK1" ON "SYSTEM"."CATALOG_UNIVERSITATE" ("ID_NOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATALOG_UNIVERSITATE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CATALOG_UNIVERSITATE_UK" ON "SYSTEM"."CATALOG_UNIVERSITATE" ("NR_MATRICOL", "ID_D", "DATA", "TIP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISCIPLINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DISCIPLINE_PK" ON "SYSTEM"."DISCIPLINE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DISCIPLINE_NUME_DISCIPLINA_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DISCIPLINE_NUME_DISCIPLINA_UK" ON "SYSTEM"."DISCIPLINE" ("NUME_DISCIPLINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INREGISTRARI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INREGISTRARI_PK" ON "SYSTEM"."DISCIPLINE_STUDENTI" ("NR_MATRICOL", "ID_D") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREZENTE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREZENTE_PK1" ON "SYSTEM"."PREZENTE" ("ID_PREZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREZENTE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREZENTE_UK" ON "SYSTEM"."PREZENTE" ("DATA", "NR_MATRICOL", "ID_D") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSOANE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERSOANE_PK" ON "SYSTEM"."STUDENTI" ("NR_MATRICOL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CNP_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CNP_UK" ON "SYSTEM"."STUDENTI" ("CNP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CATALOG_UNIVERSITATE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."CATALOG_UNIVERSITATE_TRG" 
BEFORE INSERT ON CATALOG_UNIVERSITATE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NOTA IS NULL THEN
      SELECT CATALOG_UNIVERSITATE_SEQ.NEXTVAL INTO :NEW.ID_NOTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."CATALOG_UNIVERSITATE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATALOG_VALIDARE_NOTA_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."CATALOG_VALIDARE_NOTA_TRIGGER" 
BEFORE INSERT OR UPDATE OF DATA,ID_D,NR_MATRICOL,PUNCTAJ,TIP ON CATALOG_UNIVERSITATE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
bonusDisciplina number(1,0);
examene number;
nrTesteActual number;
nrTesteMax number;
BEGIN
    IF (:NEW.DATA>SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20666, 'Data notei nu poate fi in viitor');
    END IF;
    :NEW.TIP := TRIM (:NEW.TIP);
    IF(:NEW.TIP = 'B') THEN
        SELECT BONUS
        INTO bonusDisciplina
        FROM DISCIPLINE
        WHERE ID = :NEW.ID_D;
        IF (bonusDisciplina = 0) THEN
             RAISE_APPLICATION_ERROR(-20666, 'Disciplina nu accepta puncte bonus');
        END IF;
    ELSIF(:NEW.TIP = 'E') THEN
        SELECT COUNT(*)
        INTO examene
        FROM CATALOG_UNIVERSITATE
        WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D AND TIP = 'E';
        IF (examene > 0 ) THEN
            RAISE_APPLICATION_ERROR(-20666, 'Studentul are deja o nota la acest examen!');
        END IF;
    ELSIF(:NEW.TIP = 'T') THEN
        
        SELECT NR_TESTE
        INTO nrTesteMax
        FROM DISCIPLINE
        WHERE ID = :NEW.ID_D;
        
        SELECT NR_TESTE
        INTO nrTesteActual
        FROM NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW
        WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D;
        IF (nrTesteActual = nrTesteMax) THEN
            RAISE_APPLICATION_ERROR(-20666, 'Studentul deja are inregistrare toate notele la materia respectiva');
        END IF;
        
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."CATALOG_VALIDARE_NOTA_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINA_STERGERE_BONUS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_BONUS_TRIGGER" 
AFTER UPDATE OF BONUS ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  IF (:NEW.BONUS = 0) THEN
        DELETE FROM CATALOG_UNIVERSITATE
        WHERE ID_D = :NEW.ID AND TIP = 'B';
  END IF;
END;				 
				
/
ALTER TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_BONUS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINA_STERGERE_TESTE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_TESTE_TRIGGER" 
BEFORE UPDATE OF NR_TESTE ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
type vector is table of number;
nrmSD vector;
nrTesteStudent number;
difNrT number;
BEGIN
    IF (:NEW.NR_TESTE = 0) THEN
        :NEW.PROCENT_TESTE := 0;
        :NEW.PROCENT_EXAMEN := 100;
    END IF;
    IF (:NEW.NR_TESTE < :OLD.NR_TESTE) THEN
        SELECT NR_MATRICOL
        BULK COLLECT
        INTO nrmSD
        FROM DISCIPLINE_STUDENTI
        WHERE ID_D = :NEW.ID;
        
        FOR i IN 1..nrmSD.count LOOP
            SELECT NR_TESTE
            INTO nrTesteStudent
            FROM NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW
            WHERE ID_D = :NEW.ID AND NR_MATRICOL = nrmSD(i);
            difNrT := nrTesteStudent - :NEW.NR_TESTE;
            IF (difNrT > 0) THEN
                DELETE FROM CATALOG_UNIVERSITATE
                WHERE ID_NOTA IN
                (
                    SELECT ID_NOTA
                    FROM
                    (
                        SELECT *
                        FROM CATALOG_UNIVERSITATE 
                        WHERE NR_MATRICOL = nrmSD(i) AND ID_D = :NEW.ID AND TIP = 'T'
                        ORDER BY DATA DESC
                    )
                    WHERE rownum <=difNrT
                );
            END IF;
        END LOOP;
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_TESTE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINE_PREZENTE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINE_PREZENTE_TRIGGER" 
BEFORE INSERT OR UPDATE OF PREZENTE_MINIME_ANG,PREZENTE_MINIME_NANG ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  :NEW.PREZENTE_MINIME_ANG := ROUND(:NEW.PREZENTE_MINIME_NANG * 7 / 10);
END;				 
				
/
ALTER TRIGGER "SYSTEM"."DISCIPLINE_PREZENTE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINE_TRG" 
BEFORE INSERT ON DISCIPLINE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DISCIPLINE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."DISCIPLINE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUME_DISCIPLINA_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."NUME_DISCIPLINA_TRIGGER" 
BEFORE INSERT OR UPDATE OF NUME_DISCIPLINA ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  :NEW.NUME_DISCIPLINA := TRIM(UPPER(:NEW.NUME_DISCIPLINA));
END;				 
				
/
ALTER TRIGGER "SYSTEM"."NUME_DISCIPLINA_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERSOANE_CNP_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PERSOANE_CNP_TRIGGER" 
BEFORE INSERT OR UPDATE OF CNP ON "STUDENTI" 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
    s NUMBER(4,0):=0;
    c CHAR(12) :='279146358279';
BEGIN
    :NEW.CNP := TRIM(:NEW.CNP);
    IF LENGTH(:NEW.CNP) != 13 THEN
       RAISE_APPLICATION_ERROR(-20666, 'CNP Invalid');
    END IF;
    
    FOR i IN 1..12
    LOOP
        s:=s+TO_NUMBER(SUBSTR(:NEW.CNP,i,1))*TO_NUMBER(SUBSTR(c,i,1));
    END LOOP;
    s:=MOD(s,11);
    IF s=10 THEN
        s:=1;
    END IF;
    IF s != TO_NUMBER(SUBSTR(:NEW.CNP,13,1)) THEN
        RAISE_APPLICATION_ERROR(-20666, 'CNP Invalid');
    END IF;
END;				 
				
/
ALTER TRIGGER "SYSTEM"."PERSOANE_CNP_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREZENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PREZENTE_TRG" 
BEFORE INSERT ON PREZENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PREZ IS NULL THEN
      SELECT PREZENTE_SEQ.NEXTVAL INTO :NEW.ID_PREZ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PREZENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREZENTE_VALIDARE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PREZENTE_VALIDARE_TRIGGER" 
BEFORE INSERT OR UPDATE OF DATA,ID_D,NR_MATRICOL ON PREZENTE 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
    nrPrez number;
    dataCurenta date;
BEGIN
  IF (:NEW.DATA>SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20666, 'Data prezentei nu poate fi in viitor');
    END IF;
    SELECT COUNT (*) 
    into nrPrez
    FROM PREZENTE 
    WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D;
  IF(nrPrez >= 14) THEN
    RAISE_APPLICATION_ERROR(-20666, 'Studentul are deja 14 prezente');
  END IF;
END;
/
ALTER TRIGGER "SYSTEM"."PREZENTE_VALIDARE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STUDENTI_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."STUDENTI_TRG" 
BEFORE INSERT ON STUDENTI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NR_MATRICOL IS NULL THEN
      SELECT STUDENTI_SEQ.NEXTVAL INTO :NEW.NR_MATRICOL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."STUDENTI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIM_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRIM_TRIGGER" 
BEFORE INSERT OR UPDATE OF PRENUME,NUME,NRTEL,EMAIL,ADRESA ON STUDENTI 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
    :NEW.NUME := TRIM(UPPER(:NEW.NUME)); 
    :NEW.PRENUME := TRIM(UPPER(:NEW.PRENUME)); 
    :NEW.NRTEL := TRIM(:NEW.NRTEL);
    :NEW.EMAIL := TRIM(:NEW.EMAIL);
    :NEW.ADRESA := TRIM(:NEW.ADRESA);
END;
/
ALTER TRIGGER "SYSTEM"."TRIM_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATALOG_VALIDARE_NOTA_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."CATALOG_VALIDARE_NOTA_TRIGGER" 
BEFORE INSERT OR UPDATE OF DATA,ID_D,NR_MATRICOL,PUNCTAJ,TIP ON CATALOG_UNIVERSITATE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
bonusDisciplina number(1,0);
examene number;
nrTesteActual number;
nrTesteMax number;
BEGIN
    IF (:NEW.DATA>SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20666, 'Data notei nu poate fi in viitor');
    END IF;
    :NEW.TIP := TRIM (:NEW.TIP);
    IF(:NEW.TIP = 'B') THEN
        SELECT BONUS
        INTO bonusDisciplina
        FROM DISCIPLINE
        WHERE ID = :NEW.ID_D;
        IF (bonusDisciplina = 0) THEN
             RAISE_APPLICATION_ERROR(-20666, 'Disciplina nu accepta puncte bonus');
        END IF;
    ELSIF(:NEW.TIP = 'E') THEN
        SELECT COUNT(*)
        INTO examene
        FROM CATALOG_UNIVERSITATE
        WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D AND TIP = 'E';
        IF (examene > 0 ) THEN
            RAISE_APPLICATION_ERROR(-20666, 'Studentul are deja o nota la acest examen!');
        END IF;
    ELSIF(:NEW.TIP = 'T') THEN
        
        SELECT NR_TESTE
        INTO nrTesteMax
        FROM DISCIPLINE
        WHERE ID = :NEW.ID_D;
        
        SELECT NR_TESTE
        INTO nrTesteActual
        FROM NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW
        WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D;
        IF (nrTesteActual = nrTesteMax) THEN
            RAISE_APPLICATION_ERROR(-20666, 'Studentul deja are inregistrare toate notele la materia respectiva');
        END IF;
        
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."CATALOG_VALIDARE_NOTA_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATALOG_UNIVERSITATE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."CATALOG_UNIVERSITATE_TRG" 
BEFORE INSERT ON CATALOG_UNIVERSITATE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NOTA IS NULL THEN
      SELECT CATALOG_UNIVERSITATE_SEQ.NEXTVAL INTO :NEW.ID_NOTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."CATALOG_UNIVERSITATE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINE_PREZENTE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINE_PREZENTE_TRIGGER" 
BEFORE INSERT OR UPDATE OF PREZENTE_MINIME_ANG,PREZENTE_MINIME_NANG ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  :NEW.PREZENTE_MINIME_ANG := ROUND(:NEW.PREZENTE_MINIME_NANG * 7 / 10);
END;				 
				
/
ALTER TRIGGER "SYSTEM"."DISCIPLINE_PREZENTE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUME_DISCIPLINA_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."NUME_DISCIPLINA_TRIGGER" 
BEFORE INSERT OR UPDATE OF NUME_DISCIPLINA ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  :NEW.NUME_DISCIPLINA := TRIM(UPPER(:NEW.NUME_DISCIPLINA));
END;				 
				
/
ALTER TRIGGER "SYSTEM"."NUME_DISCIPLINA_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINE_TRG" 
BEFORE INSERT ON DISCIPLINE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DISCIPLINE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."DISCIPLINE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINA_STERGERE_BONUS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_BONUS_TRIGGER" 
AFTER UPDATE OF BONUS ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  IF (:NEW.BONUS = 0) THEN
        DELETE FROM CATALOG_UNIVERSITATE
        WHERE ID_D = :NEW.ID AND TIP = 'B';
  END IF;
END;				 
				
/
ALTER TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_BONUS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DISCIPLINA_STERGERE_TESTE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_TESTE_TRIGGER" 
BEFORE UPDATE OF NR_TESTE ON DISCIPLINE 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
type vector is table of number;
nrmSD vector;
nrTesteStudent number;
difNrT number;
BEGIN
    IF (:NEW.NR_TESTE = 0) THEN
        :NEW.PROCENT_TESTE := 0;
        :NEW.PROCENT_EXAMEN := 100;
    END IF;
    IF (:NEW.NR_TESTE < :OLD.NR_TESTE) THEN
        SELECT NR_MATRICOL
        BULK COLLECT
        INTO nrmSD
        FROM DISCIPLINE_STUDENTI
        WHERE ID_D = :NEW.ID;
        
        FOR i IN 1..nrmSD.count LOOP
            SELECT NR_TESTE
            INTO nrTesteStudent
            FROM NUMAR_TESTE_STUDENT_DISCIPLINA_VIEW
            WHERE ID_D = :NEW.ID AND NR_MATRICOL = nrmSD(i);
            difNrT := nrTesteStudent - :NEW.NR_TESTE;
            IF (difNrT > 0) THEN
                DELETE FROM CATALOG_UNIVERSITATE
                WHERE ID_NOTA IN
                (
                    SELECT ID_NOTA
                    FROM
                    (
                        SELECT *
                        FROM CATALOG_UNIVERSITATE 
                        WHERE NR_MATRICOL = nrmSD(i) AND ID_D = :NEW.ID AND TIP = 'T'
                        ORDER BY DATA DESC
                    )
                    WHERE rownum <=difNrT
                );
            END IF;
        END LOOP;
    END IF;
END;
/
ALTER TRIGGER "SYSTEM"."DISCIPLINA_STERGERE_TESTE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREZENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PREZENTE_TRG" 
BEFORE INSERT ON PREZENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PREZ IS NULL THEN
      SELECT PREZENTE_SEQ.NEXTVAL INTO :NEW.ID_PREZ FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PREZENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREZENTE_VALIDARE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PREZENTE_VALIDARE_TRIGGER" 
BEFORE INSERT OR UPDATE OF DATA,ID_D,NR_MATRICOL ON PREZENTE 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
    nrPrez number;
    dataCurenta date;
BEGIN
  IF (:NEW.DATA>SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20666, 'Data prezentei nu poate fi in viitor');
    END IF;
    SELECT COUNT (*) 
    into nrPrez
    FROM PREZENTE 
    WHERE NR_MATRICOL = :NEW.NR_MATRICOL AND ID_D = :NEW.ID_D;
  IF(nrPrez >= 14) THEN
    RAISE_APPLICATION_ERROR(-20666, 'Studentul are deja 14 prezente');
  END IF;
END;
/
ALTER TRIGGER "SYSTEM"."PREZENTE_VALIDARE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIM_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRIM_TRIGGER" 
BEFORE INSERT OR UPDATE OF PRENUME,NUME,NRTEL,EMAIL,ADRESA ON STUDENTI 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
    :NEW.NUME := TRIM(UPPER(:NEW.NUME)); 
    :NEW.PRENUME := TRIM(UPPER(:NEW.PRENUME)); 
    :NEW.NRTEL := TRIM(:NEW.NRTEL);
    :NEW.EMAIL := TRIM(:NEW.EMAIL);
    :NEW.ADRESA := TRIM(:NEW.ADRESA);
END;
/
ALTER TRIGGER "SYSTEM"."TRIM_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERSOANE_CNP_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PERSOANE_CNP_TRIGGER" 
BEFORE INSERT OR UPDATE OF CNP ON "STUDENTI" 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
DECLARE
    s NUMBER(4,0):=0;
    c CHAR(12) :='279146358279';
BEGIN
    :NEW.CNP := TRIM(:NEW.CNP);
    IF LENGTH(:NEW.CNP) != 13 THEN
       RAISE_APPLICATION_ERROR(-20666, 'CNP Invalid');
    END IF;
    
    FOR i IN 1..12
    LOOP
        s:=s+TO_NUMBER(SUBSTR(:NEW.CNP,i,1))*TO_NUMBER(SUBSTR(c,i,1));
    END LOOP;
    s:=MOD(s,11);
    IF s=10 THEN
        s:=1;
    END IF;
    IF s != TO_NUMBER(SUBSTR(:NEW.CNP,13,1)) THEN
        RAISE_APPLICATION_ERROR(-20666, 'CNP Invalid');
    END IF;
END;				 
				
/
ALTER TRIGGER "SYSTEM"."PERSOANE_CNP_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STUDENTI_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."STUDENTI_TRG" 
BEFORE INSERT ON STUDENTI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NR_MATRICOL IS NULL THEN
      SELECT STUDENTI_SEQ.NEXTVAL INTO :NEW.NR_MATRICOL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."STUDENTI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function LOGMNR$COL_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$COL_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
237 185
nkvJV1w6wH1y7mRApzf9mGuebNUwgxDILkhGfHQCmP8+Vi4fyqh3SG1Fyq+pCts1OlgnK761
YuzKBA4JE5DNwZzBIF/Y4ZM5eUlquVyTkOg+AodK3vQJt9NLvPITXbP42O37gO+zKr4BQEJk
ypwrP1U/Pf6MLZONN8LUaVqHCN87T14HqHs5taX7LhLXQ2lCVBE1Ll8dyB9CDOlbyvQS/lrb
+0n1pQi9IJAWySL85ChAqnTaqFJm0YeToD4lZ8UUPQqIZNoX0x73WK9OzsmdBrvEC97iduxe
PEXVkxF6xklPod6yOGBvW7DAFMBgf+LajDLVKOAwB2EAiKCXYMuTUTtMYYkCFFf4sj1rCpsj
TLth6TSru530aM2HP6bEbm3m

/
--------------------------------------------------------
--  DDL for Function LOGMNR$GSBA_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$GSBA_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
206 171
6gxi/CQwK1I5Rfwuw/SXrOGpVRYwgwLI1yfbfHRGEjNe54OE4QwRZCoA20oG536tzgcBrj+1
xE3tE8jIhAoTlUdUmkdYMmZycO1SdiJZwwt/6BrM1wHXl/E5+3Ip2NXzC9j8v4+KjkD9d5AT
p05eEsEWjU1CBTMSpjZZrXzbgFl9QNnQ+zJGjSug21f76ajs78m6anxz7vFcTcem6XpAgKjc
EXzd/ijP8qiOqwblTfnXcRslJn3MljD02u+5fh9NBctOmnaw/tOjRCFPUhY8I9gCoMptjG7U
rHEIFzHOFyxBEdulRGq4ngSgcm7l2yOdSHgNM8rO2vUH4gozvJoLE1S8GBBzG/wrvHPhACQ/
2w==

/
--------------------------------------------------------
--  DDL for Function LOGMNR$KEY_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$KEY_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
2a0 1a1
3O4I5hDO715d8A2tqbxMCflFW0owg/D319xqfC9Grfg+K6yE71zMvtNS45AyRXBk77WpI5v4
nUSfE2lbvUYgk3JHySIe28XxC3xIYYpPGQjxwa3GzPw0FN5aN6kerQQTHUBp29Dd+vLSgBaC
2pAFrq059ZvN0ZPN11XG/2RuDY7HaTQu/QffhnY8rVlNxpFmbkVidwtZQahx5qIFu9Uww/tv
o1AvhjaORi898/KiPtOqv7LpsPFbyNuMnZEG48cxtZuesMBJFP/bKtgU2DN69xiT8Pxf+N2n
g0D2ximYzZqwY/4dBQj9dyQDuXRFo40hdqtWw0L96zV6723aQ8Xp0cqBaZj2wWTI4+6Ikry9
zY0Mdm3bV8TYqsOa+zT4fnikGO0eYbTFHEiW9QUbl/UwzuERwk8p

/
--------------------------------------------------------
--  DDL for Function LOGMNR$SEQ_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$SEQ_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
249 181
++dDv/cHZatK7/vHG9lvR8DQCpYwg/D3AEhqfHQC2h6ONoOvOeHvTNX1S5GDyajM4j8vkSVz
IMw+LbYS3goujprvmrB/LUpdBF8TVvjEqZpC7MCKPXWcGnTeL7ja8C2tcOdjOpRXkwL5NmPJ
B0KqMvwepdiQDY7HUDQrBddQC1lBqHGEogWkwRJ3+2+jUC+Gpo5GTazIWS0V551NkSl3+h0W
BhkPglLbvQDPzxWTnmu4ZuJIlTiNwTf1R0WxghyyKFjES9CJsCrGT8Fn7prlF4Mr5kx1YBGf
5xaODtRnmVJgb65RlKbAN9+Xxf2QnQjKQL99RZAgsEwGVKNfx9lFKwHLGUwzjOxmIAXXYd/Z
+L9osPQJjZYkNrD0pQ==

/
--------------------------------------------------------
--  DDL for Function LOGMNR$TAB_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$TAB_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
22e 181
PRVt0FiLRPgjIhZlCZcQhnOHXQ4wgzJp2UhGfHSKrQ843hKm3gKD9swoFAS4jVcW0CsSl7W1
6banVWdjktOVM18XyRjY4ZM5eRdquSp0ZdfHl3KJPBYqPi9LXIwum30Qh7ymgO+zTKj+R1N2
nSs/TPnknfYLwcUdAfBryDQGEIMisMuE9XT5ix3sudhHa5tLJRjsBIDKlqL7zk2CH0C1NRAZ
XrP7WgavVdNS3Yikz88VupZG21hTuAGspJBgCagmNWIwi9pgCIWP3rxF4p+uMps/ABEg+MBP
6Iykm62kO6hWhVHJXkfKF/jrQFjYBTTzatr1VTcOXt/AFuagDR7isNtb//lnXh8TXyAFWyCT
ubv6GXL0aM0PP/t+DfSl

/
--------------------------------------------------------
--  DDL for Function LOGMNR$USER_GG_TABF_PUBLIC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "SYSTEM"."LOGMNR$USER_GG_TABF_PUBLIC" wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
8
272 191
Vc+i+Mga8m7/BSlvXl0J+GmParYwg/D319wCfC8CTE6Ot30G8QRR0WzR8ohw8Z/y6DuL4pL5
IDjZApnCaZgeKa1OTjLj2B2tOYZg2ZuOAPKrxo7DeBqtn0Ahw0tubS36jP4xc+d2eQebdJMD
c/U0JxdiAl0qIPzsltBjeoGAEsxUk0aubCMJmysgc2d8ojil6ixQ37D7RA0HWMkh27QdOuXF
vSwuufDunMMT8Hue9dvy4vRXj+PhuyylJSukStsxyIb234EahCXyrjDlnzbC91eoU7v5sb4D
OvtDmggQCEViyhFXwspP9P0dOObin8JENsDJeFZYr/oVAgSHa97LRKvNZgd+f//XHlpEAOP4
rNm5mF0wTCABbb7tc5c7uo09M+79i7en8g==

/
--------------------------------------------------------
--  DDL for Synonymn CATALOG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."CATALOG" FOR "SYS"."CATALOG";
--------------------------------------------------------
--  DDL for Synonymn SYSCATALOG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE SYNONYM "SYSTEM"."SYSCATALOG" FOR "SYS"."SYSCATALOG";
--------------------------------------------------------
--  Constraints for Table CATALOG_UNIVERSITATE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("PUNCTAJ" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("TIP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" ADD CONSTRAINT "CATALOG_UNIVERSITATE_PUNCTAJ_CHK" CHECK (PUNCTAJ BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("NR_MATRICOL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("ID_D" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" MODIFY ("ID_NOTA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" ADD CONSTRAINT "TP_PUNCTAJ_CHK" CHECK (TIP IN ('E','T','B')) ENABLE;
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" ADD CONSTRAINT "CATALOG_UNIVERSITATE_PK" PRIMARY KEY ("ID_NOTA")
  USING INDEX (CREATE UNIQUE INDEX "SYSTEM"."CATALOG_UNIVERSITATE_PK1" ON "SYSTEM"."CATALOG_UNIVERSITATE" ("ID_NOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" ADD CONSTRAINT "CATALOG_UNIVERSITATE_UK" UNIQUE ("NR_MATRICOL", "ID_D", "DATA", "TIP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISCIPLINE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("NUME_DISCIPLINA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("PREZENTE_MINIME_NANG" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("NR_TESTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("PROCENT_TESTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("PROCENT_EXAMEN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("BONUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "NUME_DISCIPLINA_CHK" CHECK (REGEXP_LIKE(NUME_DISCIPLINA, '^[a-zA-Z]+[a-zA-Z0-9]*$')) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "PREZENTE_MINIME_CHK" CHECK ("PREZENTE_MINIME_NANG">=0 AND "PREZENTE_MINIME_NANG"<=14) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "NR_TESTE_CHK" CHECK (NR_TESTE >= 0) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "PROCENT_TESTE_CHK" CHECK (PROCENT_TESTE BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "PROCENT_EXAMEN_CHK" CHECK (PROCENT_EXAMEN BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "BONUS_CHK" CHECK (BONUS IN (0,1)) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "PROCENTE_CHK" CHECK (PROCENT_TESTE + PROCENT_EXAMEN = 100) ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" MODIFY ("PREZENTE_MINIME_ANG" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "DISCIPLINE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE" ADD CONSTRAINT "DISCIPLINE_NUME_DISCIPLINA_UK" UNIQUE ("NUME_DISCIPLINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISCIPLINE_STUDENTI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DISCIPLINE_STUDENTI" ADD CONSTRAINT "INREGISTRARI_PK" PRIMARY KEY ("NR_MATRICOL", "ID_D")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE_STUDENTI" MODIFY ("NR_MATRICOL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DISCIPLINE_STUDENTI" MODIFY ("ID_D" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREZENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PREZENTE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREZENTE" MODIFY ("NR_MATRICOL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREZENTE" MODIFY ("ID_D" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREZENTE" MODIFY ("ID_PREZ" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREZENTE" ADD CONSTRAINT "PREZENTE_PK" PRIMARY KEY ("ID_PREZ")
  USING INDEX (CREATE UNIQUE INDEX "SYSTEM"."PREZENTE_PK1" ON "SYSTEM"."PREZENTE" ("ID_PREZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
  ALTER TABLE "SYSTEM"."PREZENTE" ADD CONSTRAINT "PREZENTE_UK" UNIQUE ("DATA", "NR_MATRICOL", "ID_D")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("CNP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("NR_MATRICOL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "NRTEL_CK" CHECK (REGEXP_LIKE (NRTEL,'^07[2-7][0-9]{7}$')) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("NRTEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "EMAIL_CK" CHECK (REGEXP_LIKE (EMAIL, '^([a-zA-Z0-9]+(-|\.|\_)*[a-zA-Z0-9]+)+@([a-zA-Z0-9]+(-|\.|\_)*[a-zA-Z0-9]+)+\.[a-z]{2,4}$')) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "NUME_CK" CHECK (REGEXP_LIKE (NUME , '^([a-z?מג??A-Z?־ֲ??]{3,}-{0,1})+$')) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "PRENUME_CK" CHECK (REGEXP_LIKE (PRENUME ,'^([a-z?מג??A-Z?־ֲ??]{3,}[-[:blank:]]{0,1})+$')) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("ANGAJAT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "ANGAJAT_CK" CHECK (ANGAJAT IN (1,0)) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" MODIFY ("SOLD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "SOLD_CK" CHECK (SOLD >= 0) ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "PERSOANE_PK" PRIMARY KEY ("NR_MATRICOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."STUDENTI" ADD CONSTRAINT "CNP_UK" UNIQUE ("CNP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATALOG_UNIVERSITATE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CATALOG_UNIVERSITATE" ADD CONSTRAINT "CATALOG_UNIVERSITATE_FK1" FOREIGN KEY ("NR_MATRICOL", "ID_D")
	  REFERENCES "SYSTEM"."DISCIPLINE_STUDENTI" ("NR_MATRICOL", "ID_D") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISCIPLINE_STUDENTI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DISCIPLINE_STUDENTI" ADD CONSTRAINT "DISCIPLINE_STUDENTI_IDD_FK" FOREIGN KEY ("ID_D")
	  REFERENCES "SYSTEM"."DISCIPLINE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."DISCIPLINE_STUDENTI" ADD CONSTRAINT "DISCIPLINE_STUDENTI_NRM_FK" FOREIGN KEY ("NR_MATRICOL")
	  REFERENCES "SYSTEM"."STUDENTI" ("NR_MATRICOL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREZENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PREZENTE" ADD CONSTRAINT "PREZENTE_FK1" FOREIGN KEY ("NR_MATRICOL", "ID_D")
	  REFERENCES "SYSTEM"."DISCIPLINE_STUDENTI" ("NR_MATRICOL", "ID_D") ON DELETE CASCADE ENABLE;
